name: Multiverse
favicon: null
layout_spectrum: 0.8014184383209795
typography_spectrum: 0.18274190183728933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4179133956786245
  lightness: 0.4786319986451417
  saturation: 0.9843036215752363
  rhythmicContrast: 0.22370420186780393
purpose: []
